# Generated by Django 5.2 on 2026-09-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=30, unique=True)),
                ('nome_aluno', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dispositivo', models.CharField(blank=True, max_length=100)),
                ('motivo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacao_ti', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcessoWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(blank=True, default=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to='wifi.solicitacaowifi')),
            ],
        ),
    ]
