# Generated by Django 5.2 on 2026-09-21 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.CharField(choices=[('unidade', 'Unidade'), ('par', 'Par'), ('caixa', 'Caixa')], default='unidade', max_length=20)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'epis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_entrega', models.DateField(auto_now_add=True)),
                ('data_proxima_troca', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_epi', to=settings.AUTH_USER_MODEL)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='epis.epi')),
            ],
            options={
                'db_table': 'entregas_epi',
                'ordering': ['-data_entrega'],
            },
        ),
    ]
