# Generated by Django 5.2 on 2026-09-21 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('setor', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_epi', to='epis.funcionario'),
        ),
    ]
