# Generated by Django 5.2 on 2026-09-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_funcionario_alter_entregaepi_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
