# Generated by Django 5.2.8 on 2026-03-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('prefixo', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('espera', 'Em Espera'), ('chamando', 'Chamando'), ('atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='espera', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('guiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guiche')),
            ],
        ),
    ]
