# Generated by Django 5.2.8 on 2026-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('preferencial', 'Preferencial')], default='normal', max_length=20),
        ),
    ]
