# Generated by Django 5.2.8 on 2026-05-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0002_senha_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
    ]
