# Generated by Django 5.2.8 on 2026-05-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0003_controlefila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='propagandas/')),
                ('video', models.FileField(blank=True, null=True, upload_to='propagandas/videos/')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
