# Generated by Django 5.2.8 on 2026-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0005_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='acao',
            field=models.CharField(default='chamando', max_length=20),
            preserve_default=False,
        ),
    ]
