# Generated by Django 5.2 on 2026-08-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0006_historico_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='senha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filas.senha'),
        ),
    ]
