# Generated by Django 5.2.8 on 2026-09-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0007_alter_historico_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='status',
            field=models.CharField(choices=[('espera', 'Em Espera'), ('chamando', 'Chamando'), ('chamando_novamente', 'Chamando_Novamente'), ('atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='espera', max_length=20),
        ),
    ]
