# Generated by Django 5.2 on 2026-06-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
