# Generated by Django 5.2 on 2026-08-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='guiche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('financeiro', 'Financeiro'), ('secretaria', 'Secretaria'), ('declaração', 'Declaração'), ('grade', 'Grade'), ('suporte', 'Suporte'), ('ti', 'TI')], max_length=20, null=True),
        ),
    ]
