# Generated by Django 6.0.4 on 2026-08-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_atendimento_guiche_alter_atendimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='aluno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('financeiro', 'Financeiro'), ('secretaria', 'Secretaria'), ('declaração', 'Declaração'), ('grade', 'Grade'), ('requerimento', 'Requerimento'), ('ementario/historico', 'Ementário/Histórico'), ('suporte', 'Suporte'), ('ti', 'TI')], max_length=20, null=True),
        ),
    ]
