# Generated by Django 6.0.4 on 2026-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_atendimento_aluno_atendimento_atendente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.CharField(blank=True, choices=[('Alessandra', 'Alessandra'), ('Rafael', 'Rafael'), ('Geovanna', 'Geovanna'), ('Dona Fátima', 'Dona Fátima'), ('Fernando', 'Fernando'), ('Jane', 'Jane')], max_length=100, null=True),
        ),
    ]
