# Generated by Django 5.2 on 2026-08-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_alter_atendimento_atendente'),
        ('filas', '0007_alter_historico_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.CharField(blank=True, choices=[('Alessandra', 'Alessandra'), ('Rafael', 'Rafael'), ('Geovanna', 'Geovanna'), ('Fátima', 'Fátima'), ('Fernando', 'Fernando'), ('Jane', 'Jane')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='senha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filas.senha'),
        ),
    ]
