# Generated by Django 6.0.4 on 2026-08-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_alter_atendimento_atendente_alter_atendimento_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.CharField(blank=True, choices=[('Alessandra', 'Alessandra'), ('Rafael', 'Rafael'), ('Geovanna', 'Geovanna'), ('Fátima', 'Fátima'), ('Fernando', 'Fernando'), ('Jane', 'Jane'), ('Ana Paula', 'Ana Paula')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('financeiro', 'Financeiro'), ('secretaria', 'Secretaria'), ('declaração', 'Declaração'), ('grade', 'Grade'), ('requerimento', 'Requerimento'), ('ementario/historico', 'Ementário/Histórico'), ('lançamento de notas', 'Lançamento de Notas'), ('suporte', 'Suporte'), ('ti', 'TI')], max_length=20, null=True),
        ),
    ]
