# Generated by Django 5.2 on 2026-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_alter_atendimento_atendente_alter_atendimento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.CharField(blank=True, choices=[('Alessandra', 'Alessandra'), ('Rafael', 'Rafael'), ('Geovanna', 'Geovanna'), ('Fátima', 'Fátima'), ('Fernando', 'Fernando'), ('Jane', 'Jane'), ('Sharon', 'Sharon')], max_length=100, null=True),
        ),
    ]
