# Generated by Django 5.2 on 2026-10-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0008_alter_atendimento_atendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('financeiro', 'Financeiro'), ('secretaria', 'Secretaria'), ('declaração', 'Declaração'), ('grade', 'Grade'), ('requerimento', 'Requerimento'), ('ementario/historico', 'Ementário/Histórico'), ('lançamento de notas', 'Lançamento de Notas'), ('suporte', 'Suporte'), ('ti', 'TI')], max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='atendimento',
            table='atendimentos_django',
        ),
    ]
