# Generated by Django 5.2.8 on 2026-05-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('preferencial', 'Preferencial')], max_length=20)),
                ('status', models.CharField(choices=[('espera', 'Em espera'), ('chamando', 'Chamando'), ('finalizado', 'Finalizado')], default='espera', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('chamada_em', models.DateTimeField(blank=True, null=True)),
                ('guiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guiche')),
            ],
        ),
    ]
